project:
  type: website
  output-dir: docs

website:
  title: "Quarto RevealJS"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - presentation.qmd

format:
  html:
    theme: cosmo
    # css: styles.css
    toc: true

execute:
  freeze: auto
